namespace :categories do
  desc 'Refresh lib/arxiv/downloader/categories.yaml from arxiv.org/category_taxonomy'
  task :update do
    require 'date'
    require 'nokogiri'
    require 'yaml'
    require_relative '../lib/arxiv/downloader'

    taxonomy_url = 'https://arxiv.org/category_taxonomy'
    output_path  = File.expand_path '../lib/arxiv/downloader/categories.yaml', __dir__

    client = Arxiv::Downloader::Client.new rate_limit: 0
    document = Nokogiri::HTML client.get(taxonomy_url).to_s

    categories = {}
    group      = nil
    document.css('h2.accordion-head, h4').each do |node|
      if node.name == 'h2'
        group = node.text.strip
        next
      end

      text = node.text.strip.gsub(/\s+/, ' ')
      next if text == 'Category Name (Category ID)'

      match = text.match(/\A(\S+)\s+\((.+)\)\z/)
      next unless match

      id   = match[1]
      name = match[2]
      categories[id] = { 'name' => name, 'group' => group }
    end

    groups_count = categories.values.map { |entry| entry['group'] }.uniq.length
    header = <<~COMMENT
      # Generated by `rake categories:update` on #{Date.today.iso8601}
      # Source: #{taxonomy_url}
      # #{categories.length} categories across #{groups_count} groups
    COMMENT

    File.write output_path, "#{header}#{categories.to_yaml}"

    puts "wrote #{categories.length} categories to #{output_path}"
  end
end
